### ISSUE TITLE
~/Library/Application\ Support/trguing.json doesn’t get written to until app close

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#71] opened 2023-09-09 03:32 UTC
It appears that `~/Library/Application\ Support/trguing.json` doesn't get written until app exit. I added five new servers and looked at the file and they weren't in there, then closed the app and looked at the file again and they were there. Seems like it could cause data loss if the app doesn't close cleanly, and would explain why TML lost some settings when his machine rebooted for an update.

**Comment by qu1ck** [comment] 2023-09-09 03:48
This is by design. Settings should not be written every time something changes because a lot of events on the front end side can trigger very frequent updates. It will boggle down the file system with a lot of unnecessary writes.

App not closing cleanly is the actual issue that should be dealt with when that happens.

**Closed by qu1ck** 2023-09-09 03:48 UTC
