### ISSUE TITLE
Directories filter won't work for me at all

### ISSUE THREAD

**Issue by FunFrog-BY** [openscopeproject/TrguiNG#98] opened 2023-10-20 17:32 UTC
Everything works good and fast for me except directories in sidebar won't work at all: https://disk.yandex.com/i/I1O1Km_7aQfmXQ
They just doesn't show anything. I tried to wait maybe 5 minutes with no success.
Labels and trackers are working tho.

`Version
v0.9.0
Frontend
Edge 118.0.2088.46 (Blink 118.0.0.0) on Windows 10
Build date
19.09.2023, 10:13:27`

**Comment by FunFrog-BY** [comment] 2023-10-20 17:39
Also it would be nice to have option to display directories in more compact way without redundancies: https://disk.yandex.com/i/qKczwJ3swr57Mw

**Comment by qu1ck** [comment] 2023-10-20 22:50
It's supposed to be a tree view, looks like it's not working at all with windows paths.

**Comment by qu1ck** [comment] 2023-10-21 00:22
I can't reproduce this. For me transmission 4.0.4 (which you have) has "/" path separators even on windows and the directory filter works as expected.
Are your torrents added in 4.0.4 or inherited from older transmission version? Maybe it used to have "\" separators and updating transmission to new version does not change paths.

I'll add some code to be flexible with this but I'll need your help to confirm it works.

**Comment by qu1ck** [comment] 2023-10-21 02:46
Please try this build
[TrguiNG_0.9.0_x64-setup.exe.zip](https://github.com/openscopeproject/TrguiNG/files/13059548/TrguiNG_0.9.0_x64-setup.exe.zip)

**Comment by FunFrog-BY** [comment] 2023-10-21 02:47
Most of my torrents are from older versions, but some has been added since 4.0.4. Thay all had and having now same paths, same as on my first screenshot, When i tried to add torrents with TrguiNG using Browse button it added torrents with inverted slashes in path, but they downloaded and saved anyway. Now i added a new torrent again, but entered path myself with correct slash (\) and it downloaded fine too.

Ok ill try it rn.

**Comment by FunFrog-BY** [comment] 2023-10-21 02:52
Now it looks like a tree but still shows nothing 
![изображение](https://github.com/openscopeproject/TrguiNG/assets/9034852/2227b5ba-e15d-4b55-895c-f5f8cdf290c8)

**Comment by qu1ck** [comment] 2023-10-21 03:21
That still does not look right. But I found the root issue I think, this one should work

[TrguiNG_0.9.0_x64-setup.exe.zip](https://github.com/openscopeproject/TrguiNG/files/13059704/TrguiNG_0.9.0_x64-setup.exe.zip)

**Comment by FunFrog-BY** [comment] 2023-10-21 12:49
Yep, it works now! Thank you very much!

**Comment by qu1ck** [comment] 2023-10-21 21:00
Great, thanks for confirming.

**Comment by qu1ck** [comment] 2023-10-28 14:27
Fixed in [v0.10.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.10.0).

**Closed by qu1ck** 2023-10-28 14:27 UTC
Labels: bug, fix-committed
