### ISSUE TITLE
ISSUE: Download directories history not saved when serveur connection broken

### ISSUE THREAD

**Issue by Algwyn** [openscopeproject/TrguiNG#228] opened 2024-09-05 10:14 UTC
I have found that the download directories history is not saved when the server connection is unexpectedly broken.
For example, connecting to the transmission server through VPN, the VPN may disconnect. After resuming the  VPN connection and the connection to the transmission server, the latest directories added to the history have disappeared.

Would it be possible to save this history more regularly to avoid this issue? For example each time a new directory has been added to the list?

**Comment by qu1ck** [comment] 2024-09-05 10:24
You are talking about web gui, right?

For web gui config, including the directories history is saved whenever the page goes out of focus, i.e. you close it or switch to other tab. In theory it should have triggered when your connection broke too.

Which browser are you using? How did the broken connection manifest? Did the whole page disappear or did you get an error message in TrguiNG interface?

**Comment by Algwyn** [comment] 2024-09-06 08:16
I'm using the desktop macOS version v1.3.0, Frontend WebKit 605.1.15 (WebKit 605.1.15) on Mac OS 10.15.7

No error message in TrguiNG when the connection is broken. This usually occurs when the TrguiNG window is not active or visible.
An example is when the computer goes to sleep, or after switching to a different user, the VPN is broken.
The transmission window become blank, with an error message "Failed to load session. Load failed". The app reconnects to the serveur very easily after the VPN is up again. Worse case, it needs a right click on "Reload" to reconnect.

As far as I could determine, when the history is lost, it reverts to the history which was saved the last time the app was cleanly terminated (user interface Quit, or computer clean shutdown). As the app is very stable and is rebooted very occasionally, this means that several weeks of history may be lost.

**Comment by qu1ck** [comment] 2024-09-06 08:47
> Worse case, it needs a right click on "Reload" to reconnect.

That's where the issue is, that will indeed lose the history. Instead of reload just reopen the app.

I'll add some logic to save the config more often, just in case.

**Closed** 2024-09-06 11:06 UTC
