### ISSUE TITLE
White screen when clicking on Peers tab

### ISSUE THREAD

**Issue by JustAndreww** [openscopeproject/TrguiNG#158] opened 2024-02-07 19:33 UTC
Looks like a bug in WebView2:
![image](https://github.com/openscopeproject/TrguiNG/assets/4374611/4e41cf4e-412d-4329-b4bc-f4b07285391c)

Happens when there are some actual peers and download is in progress.
Is there any logs that I can provide to fix this behavior?
Setting `WEBKIT_DISABLE_DMABUF_RENDERER=1` in system variables doesn't seem to work either.

OS: Windows 10 (22H2, 19045.2604)
GPU: RXT 3060
WebView2 runtime ver: 121.0.2277.98
TrguiNG ver: [v1.1.0](https://github.com/openscopeproject/TrguiNG/tree/v1.1.0)

**Comment by qu1ck** [comment] 2024-02-07 20:07
Press F12 to open dev tools and copy any javascript errors you see there.

`WEBKIT_DISABLE_DMABUF_RENDERER=1` is only for linux and only for cases where the app is white screen from the start. Your case is definitely a javascript error.

**Comment by qu1ck** [comment] 2024-02-07 20:14
Note: you can get out of this state without reloading the app by pressing F5 to reload just the frontend.

**Comment by JustAndreww** [comment] 2024-02-07 20:26
You can also try to reproduce it by moving between the torrents in the list using keyboard ARROW UP or ARROW DOWN keys. Just press and hold one of those keys and eventually you should get a white screen :)

**Comment by qu1ck** [comment] 2024-02-07 21:42
Thanks, I couldn't reproduce it until I forced geoip lookup to fail, should be fixed now.

**Comment by qu1ck** [comment] 2024-02-21 06:20
Fixed in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)

**Closed by qu1ck** 2024-02-21 06:20 UTC
Labels: fix-committed
