### ISSUE TITLE
Scrolling through Torrents

### ISSUE THREAD

**Issue by username227** [openscopeproject/TrguiNG#61] opened 2023-08-15 17:23 UTC
Hi,
There doesn't seem to be a way to scroll through torrents on the list by pressing the up and down arrows. (Unless i'm just being stupid, which is possible). If you could enable this, it would be helpful. Thanks!

**Comment by qu1ck** [comment] 2023-08-15 23:05
Arrow keys do scroll the list but they don't change the selection/current torrent. If that is what you mean then this is a duplicate of #46

**Comment by qu1ck** [comment] 2023-09-09 05:43
This is a duplicate of either #46 or #72

**Closed by qu1ck** 2023-09-09 05:43 UTC
